package com.thoughtworks.fjw.utils;

public enum LogCode {
	END_OF_MERGING_BUCKETS,
	END_OF_TEST_RUN,
	FILL_BUCKETS,
	FORK,
	INVOKE,
	JOIN,
	MERGE_BUCKETS,
	PREPARE_BUCKETS,
	SORT_ALL_BUCKETS,
	SORT_SINGLE_BUCKET
}
